samples: 'config/samples.tsv'
units: 'config/units.tsv'
joint_calling_groups: 'config/joint_calling_groups.tsv'

ref:
    species: 'saccharomyces_cerevisiae'
    release: '98'
    build: 'R64-1-1'

bwa_index:
  mem_mb: 369000

fastp_se:
  adapter: ''
  extra: '--correction'
  threads: 2

fastp_pe:
  adapter: ''
  extra: '--correction'
  threads: 2

bwa_mem:
  wrapper: 'bwa-mem2/mem' # bwa/mem or bwa-mem2/mem
  extra: ''
  sort: 'samtools'
  sort_order: 'coordinate'
  sort_extra: ''
  threads: 8

samtools_merge:
  params: ''
  threads: 8

samtools_index:
  params: ''

deepvariant:
  model: 'wgs'
  extra: ''
  params: ''
  threads: 8

deepvariant_gvcf:
  model: 'wgs'
  extra: ''
  params: ''
  threads: 8

glnexus:
  config: 'DeepVariantWGS'
  threads: 8

bcftools_index:
  extra: ''
  threads: 8

bcftools_merge:
  params: '--force-samples'

bcftools_filter:
  filter: ''
