name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -c conda-forge mamba
    - name: Lint with flake8
      run: |
        mamba install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        mamba install -c conda-forge -c bioconda pytest snakemake singularity
        pytest .tests/unit

  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.17.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: --lint

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - unit_tests
      - linting
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    
    - name: snakemake
      uses: snakemake/snakemake-github-action@v1.17.0
      with:
        directory: .tests/integration
        snakefile: workflow/Snakefile
        args: --use-conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache
